theme: jekyll-thene-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fdalle2%2Fcomments%2Fwils8g%2Fa_mind_blown_mad_scientist_cat_digital_art%2F&psig=AOvVaw2kBb2cwIP4z-JM-76AnskX&ust=1717608599193000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPjv7YG9woYDFQAAAAAdAAAAABAE
title: Introductory Bioinformatics Lab - Linh Tran
